version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build_and_push:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            which aws
            aws --version

# aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 489994096722.dkr.ecr.us-west-1.amazonaws.com

workflows:
  my-workflow:
    jobs:
      - build_and_push:
          context:
            - test