version: 2.1

orbs:
  slack: circleci/slack@4.3.0
  aws-cli: circleci/aws-cli@3.1

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1            
          


jobs:
  build_and_push:
    machine:
      image: ubuntu-2004:2022.10.1

    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Install dependencies
          command: |
            pip install ecs-deploy
      - run:
          name: Build & Push
          command: |
            make build-image
      - run:
          name: Deploying
          command: |
            make deploy-task

      - notify_slack_error
      - notify_slack_pass
            
workflows:
  my-workflow:
    jobs:
      - build_and_push:
          context:
            - test