version: 2.1

# orbs:
#   aws-cli: circleci/aws-cli@3.1
#   aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build_and_push:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-west-1
            aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 489994096722.dkr.ecr.us-west-1.amazonaws.com

# curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
# unzip awscliv2.zip
# sudo ./aws/install


# aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 489994096722.dkr.ecr.us-west-1.amazonaws.com

workflows:
  my-workflow:
    jobs:
      - build_and_push:
          context:
            - test