version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build_and_push:
    executor: aws-cli/default
    steps:
      - checkout
      # - run: make ecr-login ECR_REPO=${ecr_login}
      - run: aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 489994096722.dkr.ecr.us-west-1.amazonaws.com
    # aws-access-key-id: ${ACCESS_KEY_ID}
    # aws-secret-access-key: ${SECRET_ACCESS_KEY}
    # dockerfile: Dockerfile
    # region: ${AWS_REGION}
    # repo: ${ECR_repository}
    # tag: 'latest, $CIRCLE_SHA1'

workflows:
  my-workflow:
    jobs:
      - build_and_push:
          context:
            - test